var annotated_dup =
[
    [ "AStarStrategy", "classAStarStrategy.html", "classAStarStrategy" ],
    [ "Car", "classCar.html", null ],
    [ "CongestionModel", "classCongestionModel.html", "classCongestionModel" ],
    [ "DijkstraStrategy", "classDijkstraStrategy.html", "classDijkstraStrategy" ],
    [ "DisjointSet", "structDisjointSet.html", null ],
    [ "EdgeKeyHash", "structEdgeKeyHash.html", null ],
    [ "EdgeState", "structEdgeState.html", "structEdgeState" ],
    [ "Graph", "classGraph.html", "classGraph" ],
    [ "GraphVisualizer", "classGraphVisualizer.html", null ],
    [ "HighwayGenerator", "classHighwayGenerator.html", "classHighwayGenerator" ],
    [ "IDMParams", "structIDMParams.html", "structIDMParams" ],
    [ "Intersection", "classIntersection.html", "classIntersection" ],
    [ "LeaderInfo", "structLeaderInfo.html", "structLeaderInfo" ],
    [ "MotorwayGenerator", "classMotorwayGenerator.html", "classMotorwayGenerator" ],
    [ "Road", "classRoad.html", "classRoad" ],
    [ "RoadGenerator", "classRoadGenerator.html", "classRoadGenerator" ],
    [ "RouteStrategy", "classRouteStrategy.html", "classRouteStrategy" ],
    [ "Simulation", "classSimulation.html", "classSimulation" ],
    [ "StreetGenerator", "classStreetGenerator.html", "classStreetGenerator" ],
    [ "TrafficEvents", "classTrafficEvents.html", "classTrafficEvents" ],
    [ "Truck", "classTruck.html", null ],
    [ "Vehicle", "classVehicle.html", "classVehicle" ]
];