var annotated_dup =
[
    [ "AStarStrategy", "classAStarStrategy.html", "classAStarStrategy" ],
    [ "Car", "classCar.html", null ],
    [ "CongestionModel", "classCongestionModel.html", "classCongestionModel" ],
    [ "DijkstraStrategy", "classDijkstraStrategy.html", "classDijkstraStrategy" ],
    [ "DisjointSet", "structDisjointSet.html", null ],
    [ "EdgeKeyHash", "structEdgeKeyHash.html", null ],
    [ "EdgeState", "structEdgeState.html", "structEdgeState" ],
    [ "Graph", "classGraph.html", "classGraph" ],
    [ "GraphDrawData", "structGraphDrawData.html", "structGraphDrawData" ],
    [ "HighwayGenerator", "classHighwayGenerator.html", "classHighwayGenerator" ],
    [ "IDMParams", "structIDMParams.html", "structIDMParams" ],
    [ "Intersection", "classIntersection.html", "classIntersection" ],
    [ "LeaderInfo", "structLeaderInfo.html", "structLeaderInfo" ],
    [ "MotorwayGenerator", "classMotorwayGenerator.html", "classMotorwayGenerator" ],
    [ "Parameters", "classParameters.html", null ],
    [ "Road", "classRoad.html", "classRoad" ],
    [ "RoadGenerator", "classRoadGenerator.html", "classRoadGenerator" ],
    [ "RouteStrategy", "classRouteStrategy.html", "classRouteStrategy" ],
    [ "SfmlSettingsWindow", "classSfmlSettingsWindow.html", "classSfmlSettingsWindow" ],
    [ "SfmlSimulationVisualizer", "classSfmlSimulationVisualizer.html", "classSfmlSimulationVisualizer" ],
    [ "SfmlStatsPanel", "classSfmlStatsPanel.html", "classSfmlStatsPanel" ],
    [ "Simulation", "classSimulation.html", "classSimulation" ],
    [ "SimulationVisualizer", "classSimulationVisualizer.html", "classSimulationVisualizer" ],
    [ "StatsSnapshot", "structStatsSnapshot.html", "structStatsSnapshot" ],
    [ "StreetGenerator", "classStreetGenerator.html", "classStreetGenerator" ],
    [ "Truck", "classTruck.html", null ],
    [ "UiMargins", "structUiMargins.html", null ],
    [ "Vehicle", "classVehicle.html", "classVehicle" ],
    [ "VisualizerView", "structVisualizerView.html", "structVisualizerView" ]
];